spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${USERSERVICE_POSTGRES_DB}
    username: ${USERSERVICE_POSTGRES_USER}
    password: ${USERSERVICE_POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081
